### ISSUE TITLE
Feature Enhancement - Expose Effort value and Assigned to on card

### ISSUE THREAD

**Issue by nathonreit** [nick-myers/azure-devops-board-cards#10]
Feature Enhancement - Would it be possible to show the Effort Value and the Assigned to Value on the cards?

**Comment by nick-myers** [comment]
Hi @nathonreit - I've added 'Assignee' and 'OriginalEstimate' to the cards now.  I haven't fully implemented the ability to turn this on or off, so they are on for everyone.
