### ISSUE TITLE
Unable to Print Cards from backlog

### ISSUE THREAD

**Issue by Russweb** [nick-myers/azure-devops-board-cards#11]

**Comment by Russweb** [comment]
Using cards is critical before the sprint even starts. 
Planning sessions start by using cards on boards, moving them around, etc.
This current state of this plugin does not allow for printing from the backlog view (any backlog view) or query results set.
This means this extensions value is diminished to in-sprint only, which can be done well digitally.
The cards have lots of value pre-digital.
Can you add this feature to those views (backlogs and queries).
As the backlog view can obviously be quite large, that feature will need to have some sort of way to limit the scope of the print out to "X # of items" or "Top XXX items" or  even a filter (only those UNDER this iteration path, etc.)

**Comment by nick-myers** [comment]
Hi @Russweb I created this extension for printing cards that would be used during a sprint.  I have extended it so you can select which sprint and which issue types to include.  I don't believe I'll have time to extend it to support printing of backlogs or queries.  If anyone else would like to do so, I'll happily review and merge any pull requests.   If I ever get  a good chunk of time to look at this, I will do - but  I can't see that happening in the next 6-12 months.  I'll add this as a possible feature request to the project and close this issue.

**Comment by nick-myers** [comment]
https://github.com/nick-myers/azure-devops-board-cards/projects/1#card-22670336
