### ISSUE TITLE
TypeError: cant read property style of null

### ISSUE THREAD

**Issue by solewiler** [nick-myers/azure-devops-board-cards#12]
There are 4 user stories 20 tasks and 2 bugs in this active iteration (sprint 5). When i click print, the error message shows up, then when i click "ok"  it prints only two of them. the others dont show up  at all. Note that the parent reference box also doesnt show up in the 2 children that printed

![image](https://user-images.githubusercontent.com/6303842/59274013-6bb2bd80-8c27-11e9-802c-7ee3e292c1b0.png)

![image](https://user-images.githubusercontent.com/6303842/59274038-7a997000-8c27-11e9-9c79-5894ce29b616.png)

![image](https://user-images.githubusercontent.com/6303842/59274068-900e9a00-8c27-11e9-8aa2-a5cd0e20f93c.png)

**Comment by nick-myers** [comment]
Hi @solewiler - I had a look at this, it appears that the library I was using to truncate strings (clamp.js) was creating an error.    I've removed this library in release 3.8, and pushed this to production, would you confirm the error no longer occurs?

**Comment by solewiler** [comment]
@nick-myers worked like a charm! thank you!
