### ISSUE TITLE
print screen cuts off 

### ISSUE THREAD

**Issue by Christ0phH** [nick-myers/azure-devops-board-cards#3]
When i have multiple lines of work items to print, the print screen cuts off the 3rd row when using A4 and horizontal view

**Comment by nick-myers** [comment]
Thank you @Christ0phH - do you mean A4 landscape?  I can take a look at supporting this orientation.  Is there a reason you're using landscape rather than portrait (is it a default)?

Are you able to provide a screenshot of the print preview so I can be sure I'm understanding your description correctly?

**Comment by Christ0phH** [comment]
Sorry for the misunderstanding. 
I'm using portrait mode where the items get cut off.

Sadly I can't provide a screenshot because i'm getting an error while uploading. ( i'll try later from my private machine)

**Comment by nick-myers** [comment]
![board cards print preview chrome](https://user-images.githubusercontent.com/13858363/50850261-41578e00-1371-11e9-9c83-aa6559fbff1f.png)

Here's a screenshot of what the print preview (and print out) look like for me in Chrome.

**Comment by nick-myers** [comment]
![board cards print preview chrome](https://user-images.githubusercontent.com/13858363/50850332-7bc12b00-1371-11e9-95bf-8d93e35f43de.png)
Here's a screenshot of what the print preview (and print out) look like for me, using Chrome.

**Comment by nick-myers** [comment]
@Christ0phH I've refactored the CSS to attempt to accommodate printing in an improved way, let me know how you get on?

**Comment by Christ0phH** [comment]
> @Christ0phH I've refactored the CSS to attempt to accommodate printing in an improved way, let me know how you get on?

Hi @nick-myers, sadly my IT dept won't let me upload a picture here or on imgur or other platforms. #<3ITsecurity 
Can i mail you it instead, because that works ;)

**Comment by Christ0phH** [comment]
![411121e9-dbe0-4b3b-9b48-a20e73d99b65](https://user-images.githubusercontent.com/42636398/51236876-8aac6c80-1973-11e9-98d0-03644b289ef1.jpeg)

Hopefully this image will show the problem, took some time to get that image here ;)

**Comment by nick-myers** [comment]
Hi @Christ0phH thanks for the screenshot - shows me something is not working the way I expected it to.

I've just updated the extension and completely thrown out all the CSS, and replaced it with:

1. https://github.com/cognitom/paper-css
2. https://necolas.github.io/normalize.css/

And implemented "proper" paging (15 'cards' per page).

Would you give it another test drive and see if it's any better now?

**Comment by Christ0phH** [comment]
> Hi @Christ0phH thanks for the screenshot - shows me something is not working the way I expected it to.
> 
> I've just updated the extension and completely thrown out all the CSS, and replaced it with:
> 
> 1. https://github.com/cognitom/paper-css
> 2. https://necolas.github.io/normalize.css/
> 
> And implemented "proper" paging (15 'cards' per page).
> 
> Would you give it another test drive and see if it's any better now?

1.1.26? ... Could yout tag the issue with the proposed fixed versions?

**Comment by nick-myers** [comment]
@Christ0phH - I've tagged the issue with the 1.1.26 milestone - I need to commit the code to github, so once I've done that, and you've confirmed it's fixed the issue, I'll close this issue.

**Comment by nick-myers** [comment]
Pushed the changes to github.  https://github.com/nick-myers/azure-devops-board-cards/commit/31fd90b1dbea49d9c8e275b441da461125c67e37

**Comment by Christ0phH** [comment]
Your fix has resolved the issue and i was able to print out the workitems without any cuts at the end of the page. 

I look forward to any update you will do on this.
