### ISSUE TITLE
Error: VS403474 when more than 200 work items are returned for @currentIteration (causes blank Page displaying when clicking the Print button)

### ISSUE THREAD

**Issue by Talbot24** [nick-myers/azure-devops-board-cards#7]
Nick,    Thanks for response earlier and thought i would open one here to understand how it is grabbing the Work Items.   I have heavily customized our AzOps

Currently getting this on the request as an error which makes perfect sense.   The only problem is I am trying to print my cards from specific teams I have created so they do not have 337 items.  That is all of my teams cards for the selected sprint.     I saw this as a option for our dev teams to use on their agile boards but unable to if cant have it narrow down the work items based on the Team's board I am on clicking the print button because we will very often have over 200 items.      Let me know if you have any ideas otherwise I will continue to let the teams create them manually for their physical boards they use.  

 {"$id":"1","innerException":null,"message":"VS403474: You requested 337 work items which exceeds the limit of 200","typeName":"Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemPageSizeExceededException, Microsoft.TeamFoundation.WorkItemTracking.Server","typeKey":"WorkItemPageSizeExceededException","errorCode":0,"eventId":3200}

**Comment by nick-myers** [comment]
Hi @Talbot24 -  I haven't used AzOps for multiple teams.   

The query that is used to get all the work items at the moment is:
`SELECT [System.Id] FROM WorkItems WHERE [System.IterationPath] = @CurrentIteration'`

How do you filter the work items for your team's boards?  Perhaps I can replicate that in a generic way.

Looking at the query syntax documentation - https://docs.microsoft.com/en-gb/azure/devops/boards/queries/wiql-syntax?view=azure-devops#macros

I can see there is a macro for @project which says:

>  Use this variable to search for work items in the current project. For example, you can find all the work items in the current project.

I'm not sure this is what will help though.

As I said, if you can let me know how you're filtering work items assigned to a sprint for your team board, I'll take a look and see if can replicate that somehow.

I do have plans to add some UI for configuring the query, which may help, but it will take me some time to implement this I think.

**Comment by Talbot24** [comment]
Basically I think your just missing variable for Teams that you can build in AzOps which creates an Area Path.   I am thinking it would just be a part of your where clause to use selected teams Area Path to get work items for specific Iteration.    Syntax is maybe like this [System.AreaPath] = @TeamAreas (Just need it to use selected AreaPath the sprint board I am on and not a blanket system wide work items for current iterations.   This maybe just us so if you don't get to it we will keep doing our manual way.  

It would also be helpful if it query pulled the iteration I had selected for sprint otherwise current would work just fine too for teams if only always pulled @CurrentIteration.   See Attachment as example of a Area Path value and Sprint other than current sprint that we build out 

Thanks for your consideration on this.  

![snapofboardsprint](https://user-images.githubusercontent.com/47831970/53182000-3c1b6f00-35be-11e9-9827-ee4773892b36.jpg)

**Comment by nick-myers** [comment]
Just a quick note to say I'm looking at this now, and trying to find a simple way to allow selection of both iteration path and area path.  Fingers crossed.

**Comment by nick-myers** [comment]
An update to this issue, after a long delay, I'm about to release a new version of the extension that allows selection of iteration and area (and work item types).  Hopefully this will help cut down the number of work items returned so that the extension will work for you.

**Comment by nick-myers** [comment]
Closed and options available in v2.x https://marketplace.visualstudio.com/items?itemName=NickMyers.board-cards
