### ISSUE TITLE
Browser Console Error: No handler found on any channel for message: {"id":1,"methodName":null,"instanceId":"board-cards","params":null,"jsonrpc":"2.0"} (causes blank page displaying when clicking the Print Button)

### ISSUE THREAD

**Issue by Francesco-Galluccio** [nick-myers/azure-devops-board-cards#8]
Hi Nick, 
I have installed version 1.1.26 on TFS 2017 on prem and when I click on the Print button I am just receiving a white screen with no popup for printer selection.
The error I can see in the Browser Console is: 
No handler found on any channel for message: {"id":1,"methodName":null,"instanceId":"board-cards","params":null,"jsonrpc":"2.0"}

Any idea?
Thanks in advance.

**Comment by nick-myers** [comment]
Hi @Francesco-Galluccio - the issue doesn't immediately jump out - however I have an update in the works, in which I'll try and streamline the loading steps, which might improve matters.  Unfortunately, I don't have a TFS 2017 instance to test on, so I'll do my usual testing on Azure DevOps, and update you when a new release is ready.

**Comment by nick-myers** [comment]
@Francesco-Galluccio the extension has been re-written now - please do retry and raise a new issue if you still have any problems?
